#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using CleanArchitecture.Blazor.Application.Common.Interfaces;
using CleanArchitecture.Blazor.Application.Common.Interfaces.Identity;
using CleanArchitecture.Blazor.Domain.Common;
using CleanArchitecture.Blazor.Domain.Common.Entities;
using CleanArchitecture.Blazor.Domain.Entities;
using CleanArchitecture.Blazor.Infrastructure.Persistence;
using CleanArchitecture.Blazor.Infrastructure.Persistence.Interceptors;
using FluentAssertions;
using Mediator;
using Microsoft.EntityFrameworkCore;
using Moq;
using Npgsql;
using NUnit.Framework;

namespace CleanArchitecture.Blazor.Application.UnitTests.Persistence;

/// <summary>A project entity keyed by <c>long</c> - impossible before Pass 55, when the base fixed <c>int</c>.</summary>
public class KeyedProbe : BaseEntity<long>, IAuditableEntity
{
    public string? Note { get; set; }
    public DateTime? CreatedAt { get; set; }
    public string? CreatedById { get; set; }
    public DateTime? LastModifiedAt { get; set; }
    public string? LastModifiedById { get; set; }
}

public sealed class KeyedProbeCreated(KeyedProbe probe) : DomainEvent
{
    public KeyedProbe Probe { get; } = probe;
}

/// <summary>A real notification handler; the test mediator routes published events to it.</summary>
public sealed class KeyedProbeCreatedHandler : INotificationHandler<KeyedProbeCreated>
{
    public List<KeyedProbeCreated> Handled { get; } = new();

    public ValueTask Handle(KeyedProbeCreated notification, CancellationToken cancellationToken)
    {
        Handled.Add(notification);
        return ValueTask.CompletedTask;
    }
}

public sealed class KeyedProbeDbContext : ApplicationDbContext
{
    public const string Schema = "gx_probe_key";

    public KeyedProbeDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
    {
    }

    public DbSet<KeyedProbe> KeyedProbes => Set<KeyedProbe>();

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<KeyedProbe>().ToTable("KeyedProbes", Schema);
        base.OnModelCreating(builder);
    }
}

/// <summary>
/// Pass 55: <see cref="BaseEntity{TKey}"/> and <see cref="BaseAuditableEntity{TKey}"/> take any key,
/// and an entity on a non-int key keeps domain-event dispatch and audit stamping.
/// </summary>
/// <remarks>
/// The test project has no Mediator source generator, so a handler declared here cannot be
/// discovered by a real <c>IMediator</c>. The mock below routes what the interceptor publishes to a
/// real <see cref="INotificationHandler{TNotification}"/>: what is asserted is that the handler ran,
/// with this entity's event, after the save.
/// </remarks>
[TestFixture]
public class GenericKeyEntityTests
{
    private const string ActingUser = "keyed-user";
    private string _connectionString = null!;

    [SetUp]
    public async Task SetUp()
    {
        _connectionString = UnitTestDatabase.ConnectionString;
        await UnitTestDatabase.ResetAsync();
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = $"""
            CREATE SCHEMA IF NOT EXISTS {KeyedProbeDbContext.Schema};
            CREATE TABLE IF NOT EXISTS {KeyedProbeDbContext.Schema}."KeyedProbes" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Note" character varying(450) NULL,
                "CreatedAt" timestamp with time zone NULL,
                "CreatedById" character varying(450) NULL,
                "LastModifiedAt" timestamp with time zone NULL,
                "LastModifiedById" character varying(450) NULL);
            TRUNCATE {KeyedProbeDbContext.Schema}."KeyedProbes";
            """;
        await cmd.ExecuteNonQueryAsync();
    }

    [OneTimeTearDown]
    public async Task DropProbeTable()
    {
        await using var conn = new NpgsqlConnection(UnitTestDatabase.ConnectionString);
        await conn.OpenAsync();
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = $"DROP SCHEMA IF EXISTS {KeyedProbeDbContext.Schema} CASCADE;";
        await cmd.ExecuteNonQueryAsync();
    }

    private KeyedProbeDbContext Context(KeyedProbeCreatedHandler handler)
    {
        var accessor = new Mock<IUserContextAccessor>();
        accessor.SetupGet(x => x.Current).Returns(new UserContext(ActingUser, "keyed"));
        var clock = new Mock<IDateTime>();
        clock.SetupGet(x => x.UtcNow).Returns(new DateTime(2026, 10, 10, 12, 0, 0, DateTimeKind.Utc));
        var mediator = new Mock<IMediator>();
        mediator.Setup(x => x.Publish(It.IsAny<DomainEvent>(), It.IsAny<CancellationToken>()))
            .Returns((DomainEvent e, CancellationToken ct) =>
                e is KeyedProbeCreated created ? handler.Handle(created, ct) : ValueTask.CompletedTask);

        var options = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseNpgsql(_connectionString)
            .AddInterceptors(
                new AuditableEntityInterceptor(accessor.Object, clock.Object),
                new DispatchDomainEventsInterceptor(mediator.Object))
            .Options;
        return new KeyedProbeDbContext(options);
    }

    [Test]
    public async Task ALongKeyedEntity_RaisingAnEventOnSave_ReachesItsHandler_AndIsStamped()
    {
        var handler = new KeyedProbeCreatedHandler();
        await using var db = Context(handler);
        var probe = new KeyedProbe { Note = "first" };
        probe.AddDomainEvent(new KeyedProbeCreated(probe));
        db.KeyedProbes.Add(probe);

        await db.SaveChangesAsync();

        handler.Handled.Should().ContainSingle().Which.Probe.Should().BeSameAs(probe,
            "dispatch iterates IHasDomainEvents, not the int-keyed BaseEntity");
        probe.DomainEvents.Should().BeEmpty("published events are cleared");
        probe.Id.Should().BeGreaterThan(0L);
        probe.CreatedById.Should().Be(ActingUser, "stamping keys off IAuditableEntity, whatever the base");
        probe.CreatedAt.Should().NotBeNull();

        await using var read = Context(new KeyedProbeCreatedHandler());
        (await read.KeyedProbes.SingleAsync()).CreatedById.Should().Be(ActingUser, "and it was committed");
    }

    // ---- the hierarchy: nothing that existed changed type ----------------------------------------

    [Test]
    public void TheIntBases_AreTheGenericOnesClosedOverInt()
    {
        typeof(BaseEntity).BaseType.Should().Be(typeof(BaseEntity<int>));
        typeof(BaseAuditableEntity).BaseType.Should().Be(typeof(BaseAuditableEntity<int>));
        typeof(BaseAuditableSoftDeleteEntity).BaseType.Should().Be(typeof(BaseAuditableSoftDeleteEntity<int>));
        typeof(BaseAuditableEntity<int>).BaseType.Should().Be(typeof(BaseEntity<int>));
    }

    [Test]
    public void TheTemplatesEntities_KeepTheirDeclaredBaseAndIntKey()
    {
        foreach (var type in new[] { typeof(Document), typeof(PicklistSet), typeof(SecurityPolicy) })
        {
            type.BaseType.Should().Be(typeof(BaseAuditableEntity), type.Name);
            type.GetProperty(nameof(IEntity<int>.Id))!.PropertyType.Should().Be(typeof(int), type.Name);
            typeof(IHasDomainEvents).IsAssignableFrom(type).Should().BeTrue(type.Name);
            typeof(IAuditableEntity).IsAssignableFrom(type).Should().BeTrue(type.Name);
            typeof(IBusinessEntity).IsAssignableFrom(type).Should().BeTrue(type.Name);
        }
    }

    public class GuidKeyedThing : BaseAuditableEntity<Guid>
    {
        public string? Name { get; set; }
    }

    private sealed class GuidContext(DbContextOptions<GuidContext> options) : DbContext(options)
    {
        public DbSet<GuidKeyedThing> Things => Set<GuidKeyedThing>();
    }

    [Test]
    public void AGuidKeyedAuditableEntity_MapsItsKey_AndNotItsEvents()
    {
        using var db = new GuidContext(new DbContextOptionsBuilder<GuidContext>().UseNpgsql("Host=none").Options);
        var entity = db.Model.FindEntityType(typeof(GuidKeyedThing))!;

        entity.FindPrimaryKey()!.Properties.Single().ClrType.Should().Be(typeof(Guid));
        entity.FindProperty(nameof(GuidKeyedThing.CreatedById)).Should().NotBeNull();
        entity.GetProperties().Select(p => p.Name).Should().NotContain(nameof(IHasDomainEvents.DomainEvents));
    }
}
#nullable restore
