#nullable enable
using System.Threading.Tasks;
using CleanArchitecture.Blazor.Application.Common.Interfaces.Identity;
using CleanArchitecture.Blazor.Domain.Common.Entities;
using CleanArchitecture.Blazor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Npgsql;

namespace CleanArchitecture.Blazor.Application.UnitTests.MultiTenant;

/// <summary>
/// The entity a project would write: a plain <see cref="BaseEntity"/> - not auditable - that must
/// belong to a tenant. The template ships no such entity, so the tests of the IMustHaveTenant path
/// bring their own.
/// </summary>
public class TenantProbe : BaseEntity, IMustHaveTenant
{
    public string TenantId { get; set; } = null!;
    public string? Note { get; set; }
}

/// <summary>
/// The application's own context with <see cref="TenantProbe"/> added - so the probe goes through
/// exactly the <c>OnModelCreating</c>, filter walk and interceptor a project entity would.
/// </summary>
/// <remarks>
/// Its table lives in a schema of its own (<see cref="Schema"/>), created by
/// <see cref="EnsureTableAsync"/> and dropped by <see cref="DropAsync"/>, so the shared test
/// database's migrated schema - which the harness checks against the migrations - is never altered.
/// </remarks>
public sealed class TenantProbeDbContext : ApplicationDbContext
{
    public const string Schema = "gx_probe";

    public TenantProbeDbContext(DbContextOptions<ApplicationDbContext> options, IUserContextAccessor? accessor)
        : base(options, accessor)
    {
    }

    public DbSet<TenantProbe> Probes => Set<TenantProbe>();

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<TenantProbe>().ToTable("TenantProbes", Schema);
        base.OnModelCreating(builder);
    }

    public static async Task EnsureTableAsync(string connectionString)
    {
        await using var conn = new NpgsqlConnection(connectionString);
        await conn.OpenAsync();
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = $"""
            CREATE SCHEMA IF NOT EXISTS {Schema};
            CREATE TABLE IF NOT EXISTS {Schema}."TenantProbes" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "TenantId" character varying(450) NOT NULL,
                "Note" character varying(450) NULL);
            TRUNCATE {Schema}."TenantProbes";
            """;
        await cmd.ExecuteNonQueryAsync();
    }

    public static async Task DropAsync(string connectionString)
    {
        await using var conn = new NpgsqlConnection(connectionString);
        await conn.OpenAsync();
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = $"DROP SCHEMA IF EXISTS {Schema} CASCADE;";
        await cmd.ExecuteNonQueryAsync();
    }
}
#nullable restore
